General: Fix absolute path detection

diff --git a/wal b/wal
--- a/wal
+++ b/wal
@@ -273,33 +273,37 @@ get_args() {
             "c") rm -rf "${cache_dir}/schemes"; exit ;;
             "h") usage; exit 1 ;;
             "i")
-                # Go to the relative PATH.
-                if ! cd "${OPTARG%/*}"; then
-                    printf "%s\n" "Error: Directory '$OPTARG' doesn't exist or is inaccessible"
-                    printf "%s\n" "       Check that the directory exists or try another directory."
-                    exit 1
-                fi
+                [[ -f "${PWD}/${OPTARG/*\/}" ]] && { wal="${PWD}/${OPTARG/*\/}"; return; }
 
-                img_dir="${OPTARG##*/}"
+                if [[ -z "$wal" ]]; then
+                    # Go to the relative PATH.
+                    if ! cd "${OPTARG%/*}"; then
+                        printf "%s\n" "Error: Directory '$OPTARG' doesn't exist or is inaccessible"
+                        printf "%s\n" "       Check that the directory exists or try another directory."
+                        exit 1
+                    fi
 
-                # Iterate down a (possible) chain of symlinks.
-                while [[ -L "$img_dir" ]]; do
-                    img_dir="$(readlink "$img_dir")"
-                    cd "${img_dir%/*}" || exit
-                    img_dir="${img_dir##*/}"
-                done
+                    img_dir="${OPTARG##*/}"
 
-                # Final directory.
-                img_dir="$(pwd -P)"
-                img="${OPTARG/*\/}"
+                    # Iterate down a (possible) chain of symlinks.
+                    while [[ -L "$img_dir" ]]; do
+                        img_dir="$(readlink "$img_dir")"
+                        cd "${img_dir%/*}" || exit
+                        img_dir="${img_dir##*/}"
+                    done
 
-                if [[ -e "${img_dir}/${img}" ]]; then
-                    wal="${img_dir}/${OPTARG/*\/}"
+                    # Final directory.
+                    img_dir="$(pwd -P)"
+                    img="${OPTARG/*\/}"
 
-                else
-                    printf "%s\n" "Error: File: '${img_dir}/${img}' not found."
-                    printf "%s\n" "       Check that the file exists or try another file."
-                    exit 1
+                    if [[ -e "${img_dir}/${img}" ]]; then
+                        wal="${img_dir}/${OPTARG/*\/}"
+
+                    else
+                        printf "%s\n" "Error: File: '${img_dir}/${img}' not found."
+                        printf "%s\n" "       Check that the file exists or try another file."
+                        exit 1
+                    fi
                 fi
             ;;
 
